uber/petastorm

petastorm/reader_impl/epochs.py, petastorm/tests/test_epoch_generator.py
Epoch generator is factored out of ventilator.py and will be used in the reader_v2
=> [Part 1] New reader flow: Epoch generator

.coveragerc, .travis.yml, setup.py
=> Add codecov.io

doc/migrating-0.3.0.md
=> Adding a note about an argument in CompressedImageCodec constructor.

petastorm/tests/conftest.py, petastorm/tests/test_ngram_end_to_end.py
Caching datasets is enabled only if pytest is called with `--cache-synthetic-dataset`.
Parametrizing a test cases with reader factories enable to run the same test suite on different flavors of a Reader instance.
=> Cache datasets in integration tests if `--cache-synthetic-dataset` is enabled and parametrize test cases by a reader factory.

.travis.yml
In service of uber/petastorm#104
=> Process core dump and output backtrace after script failure

.travis.yml
In service of uber/petastorm#104...need to install `gdb` and enable core!
=> Install gdb and enable core dump

docs/troubleshoot.md
=> Add troubleshooting steps to address issue #52

docs/autodoc/conf.py, docs/development.rst
I created a repo and RTD branch so we can see what it looks like, although that branch needs not be shipped.
=> Added steps and thoughts on using sphinx-apidoc in future

petastorm/tests/test_predicates.py
It's possible that I didn't fully grok #43, but the newly added test case seems to pass.
Perhaps someone already fixed #43?!
But, this pull request is a refactoring of `test_predicates.py` to pytest form...please use diff view ignoring spaces. :-)
=> Test case added to fix #43, but found that the error doesn't occur

petastorm/reader.py, petastorm/reader_worker.py, petastorm/tests/test_end_to_end.py
I plan to add the ability to have the FilesystemResolver work with libhdfs but will do that in a separate pr once we move to the factory method for creating the reader
=> Allow passing in of pyarrow filesystem

examples/mnist/tests/test_generate_mnist_dataset.py, petastorm/reader.py, petastorm/reader_impl/epochs.py, petastorm/reader_impl/reader_v2.py, petastorm/reader_impl/row_group_decoder.py, petastorm/reader_impl/row_group_loader.py, petastorm/reader_impl/same_thread_executor.py, petastorm/reader_impl/worker_loop.py, petastorm/shuffle_options.py, petastorm/test_util/shuffling_analysis.py, petastorm/tests/test_end_to_end.py, petastorm/tests/test_epoch_generator.py, petastorm/tests/test_ngram_end_to_end.py, petastorm/tests/test_reader.py, petastorm/tests/test_row_group_decoder.py, petastorm/tests/test_same_thread_executor.py, petastorm/utils.py, setup.py
This PR contains multiple commits leading to an implementation of Reader V2.
Each commit implements a single aspect of the feature and can be reviewed independently.
worker_loop is responsible for driving data flow between loader->shuffling-buffer->decoder. It's responsibility is to move references to data from one stage to another while submitting tasks to executor pools.
=> New reader v2

docs/autodoc/index.rst, docs/autodoc/release_notes_include.rst, docs/release-notes.rst, petastorm/__init__.py
Added release notes and bump up the version number
=> Preparing v0.4.0 release

.travis.yml
Attempt to resurrect automatic publishing to pypi
=> Updated pypi encrypted password

petastorm/benchmark/throughput.py, petastorm/tests/test_benchmark.py, petastorm/tests/test_copy_dataset.py, petastorm/tests/test_spark_session_cli.py, petastorm/tests/test_unischema.py, petastorm/tools/copy_dataset.py, petastorm/tools/spark_session_cli.py, petastorm/unischema.py, setup.py
A command line utility that copies a dataset while selecting a subset of columns/rows.
=> A command line copy dataset utility

petastorm/codecs.py
=> Fixes OpenCV requirement (#186)

.travis.yml, petastorm/reader_impl/pyarrow_serializer.py, petastorm/reader_impl/same_thread_executor.py, petastorm/reader_impl/shuffling_buffer.py, petastorm/tests/conftest.py, petastorm/tests/test_common.py, petastorm/tests/test_end_to_end.py, petastorm/tests/test_pyarrow_serializer.py, petastorm/tests/test_same_thread_executor.py, petastorm/tf_utils.py, petastorm/workers_pool/process_pool.py
This part includes:
- Stricter type checks in unit tests
- Addition of `PyArrowSerializer`
The goal is to find what causes systematic failure of python3.6 build on travis
=> Splitting PR #197 into smaller pieces

docs/development.rst
Add `setuptools` upgrade to the development environment setup instructions
=> Update development environment setup instructions

petastorm/etl/dataset_metadata.py, petastorm/etl/metadata_util.py, petastorm/etl/petastorm_generate_metadata.py, petastorm/etl/rowgroup_indexing.py, petastorm/fs_utils.py, petastorm/reader.py, petastorm/reader_impl/reader_v2.py, petastorm/reader_impl/row_group_loader.py, petastorm/spark_utils.py, petastorm/tests/test_fs_utils.py, setup.py
=> Initial support for S3

petastorm/tests/test_common.py, petastorm/tests/test_end_to_end.py
when pyarrow_serialize=True, the type check is disabled since pyarrow serialization does not handle all integer types correctly
=> Fix type check in test_end_to_end

petastorm/tests/test_tf_utils.py
Makes it easier to add tests that use a reader that returns batched results later.
=> Refactor test_tf_utils

petastorm/workers_pool/process_pool.py
Use `bytes()` as a placeholder instead of `serializer.serialize(None)`.
That way, a serializer implementation does not have to handle extra data types, besides the
collection of data elements. This helps in ArrowTableSerializer: we can always assume
a pyarrow.Table to be serialized.
=> Simplify requirements from a serializer object used by ProcessPool

petastorm/hdfs/tests/test_hdfs_namenode.py
make sure it can be run by a multithreaded pytest (e.g. `pytest -n 10`)
=> Port test_hdfs_namenode.py test to pytest

docs/autodoc/index.rst, docs/autodoc/migration_guide_include.rst, docs/migrating-0.5.0.rst, docs/release-notes.rst, petastorm/__init__.py
Added release notes and migration guide
=> Updating package version number and release docs

petastorm/tests/test_tf_utils.py, petastorm/tf_utils.py
`pyarrow==0.12.1` now reads parquet `DateType` columns as python datetime object.
TF does not support conversion of this native python time. We convert datetime.date column
to the number of nano-seconds since epoch in int64 to make the column into TF friendly.
=> Convert `datetime.date` to int64 (nanosec from epoch)

petastorm/py_dict_reader_worker.py, petastorm/tests/test_end_to_end.py
Lack of synchronization in the `PyDictReaderWorkerResultsQueueReader` was resulting in some samples being missed or even crash.
=> Synchronize reading new samples from Reader.

petastorm/tests/test_decode_row.py, petastorm/utils.py
Raise DecodeFieldError exception. Added tests for `decode_row` function.
=> Make user aware of a field name that failed decoding of a row

petastorm/arrow_reader_worker.py
Previously, was assuming that 1 row-group will always map to a single chunk. Apparently, this is not the case.
=> Proper handle the case when pyarrow returns a multichunked table.

petastorm/pytorch.py, petastorm/tests/test_pytorch_dataloader.py
Added `shuffling_queue_capacity` and `min_after_dequeue` arguments to `petastorm.pytorch.DataLoader` class. When these values are set, an inmemory buffer is used to accumulate and reshuffle data being loaded. 
The mechanism is not as flexible as PyTorch's sampling which is hard to implement because of the to have an efficient random data access in Parquet files.
=> Support inter-row-group shuffling queue when reading from pytorch

petastorm/py_dict_reader_worker.py, petastorm/tests/test_end_to_end.py
It was reported in #391, that having the transform applied before predicate
does not allow us to get rid of string fields that can not be forwarded to PyTorch.
This PR changes the order of predicate/transform so that the scenario described in #391 works.
=> Apply transform function after predicate was evaluated (with make_reader)

README.rst
=> Fix pyspark hello world link

petastorm/tests/test_unischema.py
Fixed test to work with pyarrow 0.14.1. Other then that, no test functionality change.
=> Port test_unischema to pytest

petastorm/tests/test_end_to_end.py, petastorm/unischema.py
Before this change, if a user was specifying `schema_fields=[Unischame('some_field', np.int8, (), NewCodec(), ...)]`
as a `make_reader` argument, we would use the new field definition, even that `some_field`'s `UnischemaField`
object persisted with the dataset had a different type/shape/codec.
This commit makes sure we use `some_field` field-name to lookup the corresponsing field name in the persisted dataset.
This guarantees correspondance between the field definition and actual persisted data.
=> Use UnischemaField object persisted in the dataset to guarantee correct decoding

petastorm/tests/test_weighted_sampling_reader.py, petastorm/weighted_sampling_reader.py
Adding some tests to cover `WeightedSamplingReader` usage from TF as well as some newly added argument validation.
=> Fixing WeightedSamplingReader that got stale

petastorm/tests/test_unischema.py, petastorm/unischema.py
Before this change, even a substring match was considered a match. For example:
Before this change:
- field name: 'field_123' would be loaded from the dataset with `make_reader(..., schema_fields=['123'])`.
After this change, user will need to specify a regex to match the full field name, for example:
- `schema_fields=['field_123']`
- `schema_fields=['.*123']`
=> Regex specified in `make_reader`'s `schema_fields` argument now must match the entire field name.

.travis.yml, petastorm/pytorch.py, petastorm/tests/test_disk_cache.py, petastorm/tests/test_pytorch_dataloader.py
Also made some fixups to support torch 1.3 properly.
=> Upgrade petastorm CI image to 2019-11-27_13-25-17. Uses ubuntu 18.04.

docker/Dockerfile, docker/Makefile
=> Use ubuntu 18.04 as CI image

petastorm/etl/dataset_metadata.py
=> update materialize_dataset documentation for filesystem factory arg

petastorm/fs_utils.py, petastorm/gcsfs_helpers/gcsfs_wrapper.py, petastorm/reader.py, petastorm/tests/test_fs_utils.py, setup.py
=> Support GCSFS

petastorm/workers_pool/process_pool.py, petastorm/workers_pool/tests/test_workers_pool.py
If you are using Petastorm in process mode and the main process dies unexpectedly, it leaves the workers running until the user manually kills them. In some environments, this can be quite tricky, especially if you don't SSH access to the box.
I propose a solution where a each worker runs a separate thread which periodically checks if the main process is running. If the worker sees the main process has died, the worker will exit.
=> A monitor thread added to workers

petastorm/tests/test_tf_dataset.py, petastorm/tests/test_tf_utils.py, petastorm/tf_utils.py
Refactored some common code to reuse tf_tensors code that deals with
ngrams.
=> Add ngrams support to make_petastorm_dataset function.

petastorm/__init__.py
=> Deprecate python2

docs/release-notes.rst, petastorm/spark/spark_dataset_converter.py, petastorm/tests/test_spark_dataset_converter.py
Adds support for:
- Shuffling
- Custom data loaders
=> Added additional kwargs for Spark Dataset Converter

.travis.yml
Previous value of 180 made some tests flaky.
=> Set unittest timeout to 360

petastorm/codecs.py, petastorm/tests/test_codec_compressed_image.py, petastorm/tests/test_codec_ndarray.py, petastorm/tests/test_codec_scalar.py
=> Implement the __str__ method for codecs

docs/release-notes.rst, petastorm/fs_utils.py, petastorm/reader.py
=> Parameterize factory methods with s3 configs

docker/Dockerfile
Adding make and skbuild to the image
=> Fix docker file

docs/development.rst
Adding some comments related to `pyspark` and `cv2`.
=> Add comments in development.rst

.travis.yml, petastorm/__init__.py
After travis_3_6 branch passes tests after changing Travis CI python version to 3.6, pull the changes into master branch.
=> Bump up to 0.10.0rc4

docker/Dockerfile
Pin TF/Pytorch/Numpy/Pyspark versions that are known to be compatbile.
=> Facelift to Dockerfile

petastorm/tests/test_tf_dataset.py, petastorm/tf_utils.py
Change runtime error into warnings.
Add warnings check in unit tests as well.
=> tf_dataset: enable repeat() with warnings

docker/Dockerfile
This enables us to test in CI with py3.9
=> Add python 3.9 to the dockerfile used in testing

docs/release-notes.rst, petastorm/__init__.py, petastorm/fs_utils.py
=> Extraction of storage_options from URL

petastorm/pytorch.py
=> Improve a docstring of petastorm.pytorch.DataLoader class.

.github/workflows/unittest.yml
Reference: https://github.com/actions/create-release
Generated release example: https://github.com/chongxiaoc/petastorm/releases/tag/v0.12.1rc1
=> Add draft_release Actions

petastorm/spark/spark_dataset_converter.py
=> Added fsspec support for _default_delete_dir_handler

docs/release-notes.rst, petastorm/py_dict_reader_worker.py, petastorm/reader.py, petastorm/tests/test_end_to_end.py
=> Support passing multiple url files to make_reader function.
