uber/petastorm

- .travis.yml
I see ~70sec goes to pip install. Try the caching feature (caches $HOME/.cache/pip
Also make pytest output verbose to see if a test is "stuck"
> Try using travis-ci cache to speedup pip install phase

- .travis.yml
opencv and pyarrow are no longer an extra dependencies in setup.py. Removed.
> Removed no longer valid extras from .travis.yml install

- petastorm/reader_impl/epochs.py
- petastorm/reader_impl/shuffling_buffer.py
- petastorm/tests/test_epoch_generator.py
- petastorm/tests/test_shuffling_buffer.py
Items can be added to a shuffling buffer and removed in a different order as defined by the concrete shuffling algorithm.
Currently we have a `NoopShufflingBuffer` implementation which is not really shuffling, but just a FIFO implementation. Used for tests and when we don't want to shuffle.
`RandomShufflingBuffer` implements a random shuffling buffer with low and high water marks.
Shuffling buffers are not intended to be thread safe.
> [Part 2] New reader: ShufflingBuffer implementations (Random and Noop)

- petastorm/fs_utils.py
- petastorm/tests/test_end_to_end.py
Saw a failure on someone's machine. Was using 
```python 
from __future__ import unicode_literals
```
> Support passing unicode string as a dataset url.

- petastorm/reader.py
- petastorm/tests/test_reader.py
Since we moved the order of arguments this validation is important to fail fast and prevent weird errors
> Validate that dataset_url is string

- petastorm/tests/test_tf_utils.py
Setting `min_after_dequeue` to highest value possible (capacity - 1) guarantees better shuffling.
Previously was set to 0, increasing probability of the same shuffling pattern for different runs.
> Make tests verify shuffling more robust

- petastorm/tests/test_ngram_end_to_end.py
Using fixtures. Reduced run-time for the tests from 84 to 40 seconds.
> Porting ngram tests to pytest.

- petastorm/etl/dataset_metadata.py
This should be removed for 0.3.0 because it actually is no longer working (just using this will not produce the parquet summary files and thus will not create a readable dataset). I found several instances of this still being used and it produces an error only on trying to read the dataset. It it therefore better to remove it and fail fast
> Remove deprecated add_dataset_metadata function

- petastorm/ngram.py
- petastorm/reader.py
- petastorm/tests/test_ngram_end_to_end.py
This was requested by a couple people on perception. Basically helps return less correlated sequences by not overlapping timestamps.
> Add an option for NGrams to not return overlapping timestamps

- petastorm/etl/petastorm_generate_metadata.py
Makes it easier to run, when the package is not properly installed.
> Make `petastorm_generate_metadata.py` lunchable when not installed as an entry_point.

- doc/migrating-0.3.0.md
- petastorm/etl/dataset_metadata.py
- petastorm/etl/petastorm_generate_metadata.py
- setup.py
The reason for this is because to submit this as a spark job it must have a `.py` extension to run properly. Submitting as a spark job makes dealing with the permission issues easier.
> Add .py extension to metadata generation script

- petastorm/ngram.py
- petastorm/reader.py
- petastorm/reader_worker.py
- petastorm/tests/conftest.py
Two commits in this PR:
* Adding `-Y` shortcut for `--cache-synthetic-dataset`
* Obsoleting namedtuples within the reader internals implementations. Conversion to namedtuple happens right before values are returned to the user. (Resolves https://github.com/uber/petastorm/issues/91)
> -Y switch and no-namedtuples-in-reader

- petastorm/tests/conftest.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_pytorch_utils.py
No need to import it in tests. The information is present in the synthetic_dataset itself.
> Make `ROWS_COUNT` private to conftest.py

- .travis.yml
- examples/mnist/tests/conftest.py
Let's see if this helps CI builds pass.
It was leaking into non pytorch tests and triggering a crash of the tests.
Still need to figure out why the crash happens. a
> Removing early loading of pytorch.

- README.md
- examples/mnist/main.py
- petastorm/pytorch.py
Prevoiusly, a code that would create a Dataloader without transform argument would fail,
since the default transform would return None instead of being an identity function.
Also, `default_collate` function implementation does not support namedtuples, as returned by Reader.
Changed the returned types to be dictionaries which are supported ok.
> Support default transform correctly & make Dataloader return dictionaries and not lists.

- petastorm/codecs.py
- petastorm/reader.py
- petastorm/reader_worker.py
- petastorm/tests/test_codecs.py
- petastorm/tests/test_common.py
- petastorm/tests/test_end_to_end.py
- petastorm/workers_pool/process_pool.py
We use pyarrow serialization instead of standard pickling. Unfortunatelly, pyarrow serialization
does not support decimals, so we modify the codec to decode decimals always as strings.
Updated all tests to reflect the decimal->string behavior.
> Speed up processing of small row datasets with ProcessPool

- docs/autodoc/reader.rst
- petastorm/sampling_mixer.py
- petastorm/tests/test_sampling_mixer.py
`WeightedSamplingReader` takes a list of Reader objects and probabilities. When iterated over, it returns a mixture of rows returned from the readers. The mixture proportions defined by the probabilities passed to `WeightedSamplingReader` in a constructor.
`WeightedSamplingReader`  implements the same interface as `Reader`.
> Adding WeightedSamplingReader class

- petastorm/etl/petastorm_generate_metadata.py
- petastorm/tests/test_common.py
- petastorm/tests/test_end_to_end.py
Instead of calling .stop() on sqlContext object, we should do it on the main spark session.
> Correct way to stop spark

- petastorm/tests/test_weighted_sampling_reader.py
- petastorm/weighted_sampling_reader.py
Accidentally landed a `SamplingMixer` before it was renamed to `WeightedSamplingReader`. This PR renames the class to its proper name.
> Rename sampling mixer

- petastorm/etl/dataset_metadata.py
- petastorm/etl/petastorm_generate_metadata.py
- petastorm/pytorch.py
- petastorm/reader.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_generate_metadata.py
- petastorm/tests/test_metadata_read.py
- petastorm/tests/test_predicates.py
- petastorm/tests/test_pytorch_utils.py
- petastorm/tests/test_reader.py
Since we have needed to do this a few times, lets bring the legacy metadata back for now until we can figure it out more explicitly
> Revert to using the old metadata method by default

- petastorm/tests/test_end_to_end.py
There is extra randomness with reader v2 since by default it runs with 5 threads. That improves the shuffling making the test less stable.
We force a single-threaded loader and decoder implementations.
> Stabilize `petastorm/tests/test_end_to_end.py::test_shuffle_drop_ratio`

- petastorm/workers_pool/tests/test_workers_pool.py
Something is going wrong TravisCI with I suspect Process Pool tests. Disabling the tests for now
as since we did not modify workers pool recently and we are going to deprecated it soon.
> Temporary disable processpool tests.

- petastorm/tests/test_end_to_end.py
- petastorm/workers_pool/tests/test_workers_pool.py
sqlite3 + multiprocessing.Process results in a intermittent lock of a newly forked process. Exclude the test that covered that combination. 
According to https://www.sqlite.org/faq.html:
> Under Unix, you should not carry an open SQLite database across a fork() system call into the child process.
> Disable LocalDiskCache test with ProcessPoolExecutor

- petastorm/codecs.py
- petastorm/tests/test_codecs.py
- petastorm/tests/test_common.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_ngram_end_to_end.py
- petastorm/tests/test_tf_dataset.py
- petastorm/workers_pool/process_pool.py
Replacing Decimal with strings at the codec level was a bad idea. It broke a bunch of existing code.
Among others, it also broke ngrams which were relying on Decimal field for threashold checks.
In this commit, we add pyarrow_serliaze optional argument to the ProcessPool constructor, so a user
that needs pyarrow fast serialization, but is willing to sacrifice some types that can be used
in a Unischema can get faster serialization.
> Resurrect Decimal type and make pyarrow.serialize optional

- petastorm/benchmark/throughput.py
__args__ is an _undefined name_ in this context which will probably raise NameError at runtime.
__pool_type__ is an argument to this function so this PR recommends using that instead of __args.pool_type__.
[flake8](http://flake8.pycqa.org) testing of https://github.com/uber/petastorm on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./petastorm/benchmark/throughput.py:265:94: F821 undefined name 'args'
raise ValueError('Supported pool types are thread, process or dummy. Got {}.'.format(args.pool_type))
^
1     F821 undefined name 'args'
1
```
> Undefined name: args.pool_type --> pool_type in throughput.py

- .travis.yml
Fixes #175
* Add Python 3.7 in alignment with travis-ci/travis-ci#9069
* Add [flake8](http://flake8.pycqa.org) tests as discussed at https://github.com/uber/petastorm/pull/174#issuecomment-423771436
> Travis CI: Add Python 3.7 and flake8 tests

- README.rst
Non ascii character in README.rst results in a failure of `pip install -e .` on machines
without configured locale. This happens, for example, in a fresh ubuntu docker image.
> Removing non-ascii character for README.rst

- .travis.yml
This way we'll get a call stack in case of a test that hangs
> Add pytest-timeout extension for pytest

- petastorm/workers_pool/ventilator.py
If stop was called while ventilate_fn is in progress, the value of _iterations_remaining can become -1.
Introducing a separate flag to indicate forced end of ventilation.
> Fixing ventilator race condition

- petastorm/benchmark/cli.py
- petastorm/benchmark/throughput.py
- petastorm/reader.py
- petastorm/reader_impl/pickle_serializer.py
- petastorm/tests/test_benchmark.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_pickle_serializer.py
- petastorm/tests/test_reader.py
- petastorm/workers_pool/dummy_pool.py
- petastorm/workers_pool/process_pool.py
- petastorm/workers_pool/thread_pool.py
Effective control over the amount of rowgroups that are processed by process pool. The size of rowgroups allowed to be somewhere in loading/decoding is defined now by the amount of workers.
Improved the way we use pyarrow serialization and pyzmq to reduce amount of memory copies.
Improved pyarrow serialization to support decimal.Decimal type.
Improved diagnostics reported by Reader.
These are too many changes for a single PR, but they are split into small commits.
> ProcessPool output queue size control and zero copy pyarrow serialization

- .travis.yml
- setup.py
Move installation of pytest-logger into setup.py. Apparently all hooks in conftest.py need to be known to pytest, otherwise the tests fail.
> Fix running tests locally.

- petastorm/utils.py
An example of a Hive parquet store that I saw, had  `metadata` field with `None` value  in the
`pyarrow.parquet.read_metadata(f).schema.to_arrow_schema()`. In this commit, we remove an assumption
on any kind of a dictionary in that property and create a dictionary ourselves, if none could be loaded.
> Support _common_metadata generation for hive parquet stores

- .travis.yml
- petastorm/pytorch.py
- petastorm/tests/test_pytorch_dataloader.py
PyTorch supports only following integer types: int8, int32 and int64. PyTorch does not
support tensors of strings/objects. Adding an extra stage in `petastorm.pytorch.Dataloader`
that promotes unsupported integer types to the next (wider) integer type that is supported.
Raising an exception with a clear message if a value is unsupported and can not be
promoted, such as `np.string_`, `np.unicode_` or `np.object`.
> Make petastorm.pytorch.Dataloader compatible with additional integer types.

- petastorm/tests/test_end_to_end.py
It was working fast while we knew the number of rows in each rowgroup. We don't have this information now,
so there are many row-groups that are dropped without being used by shuffle_row_drop_partition feature.
The time it takes for the test to finish now is 2 seconds instead of 23 seconds (and I assume it takes more on travis)
> Make test_shuffle_drop_ratio by not setting shuffle_row_drop_partitions >> rowgroup size.

- petastorm/tests/test_end_to_end.py
Without it, the test_end_to_end will hang indefinitely.
> Recover pytest.mark.forked accidentally lost in one of the commits

- petastorm/reader.py
- petastorm/tests/test_copy_dataset.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_ngram_end_to_end.py
- petastorm/tests/test_pytorch_dataloader.py
- petastorm/tests/test_reader.py
- petastorm/workers_pool/exec_in_new_process.py
This allows us to change reader implementation in the future, without modifying user code.
> Support reader_engine=experimental_reader_v2 and reader_engine_params parameters in make_reader factory function

- petastorm/codecs.py
- petastorm/tests/test_codec_compressed_image.py
- petastorm/tests/test_codec_ndarray.py
- petastorm/tests/test_codec_scalar.py
A single test_codecs.py became messy and hard to track.
> Split codec tests into separate modules

- examples/mnist/pytorch_example.py
- petastorm/pytorch.py
- setup.py
Prints a much better error message than allowing pytorch to do type checking internally
> Print better error messages for pytorch usage

- petastorm/__init__.py
This enables doc strings and symbol navigation work smoother from within IDEs.
> Alias `make_reader` via importing it rather creating a separate symbol

- petastorm/cache.py
- petastorm/etl/__init__.py
- petastorm/etl/dataset_metadata.py
- petastorm/reader_impl/shuffling_buffer.py
- petastorm/reader_impl/worker_loop.py
- petastorm/selectors.py
- petastorm/workers_pool/__init__.py
- petastorm/workers_pool/thread_pool.py
- petastorm/workers_pool/ventilator.py
With newer version of pylint, we started getting these errors. Removing
`pass` statements where a docstring is present to avoid the failure.
> Fix "Unnecessary pass statement" lint failure

- petastorm/reader_impl/arrow_table_serializer.py
- petastorm/tests/test_arrow_table_serializer.py
ArrowTableSerializer can be used by a ProcessPool to serialize arrow tables when sending data from a worker to the main process.
> Adding ArrowTableSerializer

- petastorm/benchmark/throughput.py
- petastorm/reader.py
- petastorm/workers_pool/process_pool.py
…instead of a boolean flag.
We will need more flexibility with serializing results coming from ProcessPool when using PyArrow tables as the container for all data. `ArrowTableSerializer` is introduces as a third serialization option in another CL.
> Configure ProcessPool with a serializer object instance

- petastorm/reader.py
- petastorm/tests/test_parquet_reader.py
Now `make_batch_reader` can take a list of regex patterns as the `schema_fields` arguments.
> Allow user to specify a subset of fields to read.

- petastorm/tests/test_common.py
- petastorm/tests/test_tf_utils.py
- petastorm/tests/test_unischema.py
- petastorm/tf_utils.py
- petastorm/unischema.py
Now, we can read from a Parquet store that has native parquet dates and timestamps.
When reading into Tensorflow, the values will appear as int64 containing number of nanoseconds from unix epoch.
> Adding DateType() and Timestamp() types support

- petastorm/arrow_reader_worker.py
- petastorm/tests/test_common.py
- petastorm/tests/test_parquet_reader.py
- petastorm/tests/test_unischema.py
- petastorm/unischema.py
When reading a native dataset using `make_batch_reader`, an array types are now supported (at least numeric types) under assumption of a fixed number of elements in each list entry. The fixed number of elements assumption is required to enable batching multiple rows into a matrix.
> Support native parquet list types.

- petastorm/etl/dataset_metadata.py
- petastorm/etl/metadata_util.py
- petastorm/etl/petastorm_generate_metadata.py
- petastorm/etl/rowgroup_indexing.py
- petastorm/fs_utils.py
- petastorm/reader.py
- petastorm/reader_impl/reader_v2.py
- petastorm/reader_impl/row_group_loader.py
- petastorm/spark_utils.py
- petastorm/tools/copy_dataset.py
In methods such as `materialize_dataset` the user can supply its own fs-handle
to use libhdfs instead of libhdfs3. But in other API methods, such as `dataset_as_rdd`,
there is currently no way for the user to specify to use libhdfs over libhdfs3.
This commit fixes that.
For example, before this commit, running the following command in a libhdfs environment:
```python
dataset_as_rdd(dataset_url, spark, [HelloWorldSchema.id, HelloWorldSchema.image1])
```
would give:
```
pyarrow.lib.ArrowIOError: Unable to load libhdfs3
```
With the changes of this commit you can specify the optional argument `hdfs_driver`
```
rdd = dataset_as_rdd(dataset_url, spark, [HelloWorldSchema.id, HelloWorldSchema.image1], hdfs_driver="libhdfs")
```
so that you can overwrite default value `libhdfs3` and make it …
> Parameterize the hdfs-driver in the API to support libhdfs

- petastorm/reader.py
- petastorm/tests/test_predicates.py
#280 
Currently, if a `Reader` is initialized on a partitioned dataset with a predicate, the partition values will be interpreted as strings during predicate application, which is problematic in cases like `"1234"` where the partition value should be read as an int.
> Interpret partition values as correct type from schema when applying predicate

- petastorm/etl/rowgroup_indexing.py
This interferes with log level being set by a user.
It is responsibility of a particular entry point to decide on the log level policy. When some module changes the level, it makes it impossible to enforce the desired policy .
> Should not be setting log level explicitly in a module (not main)

- petastorm/ngram.py
- petastorm/reader.py
Fixing a bug that caused all columns of a dataset to be read when `schema_fields=NGram(...)` was used.
Now, we collect all UnischemaField instances that appears in at least one of the time offsets within an NGram and load only corresponding columns.
> Don't read unneeded columns when working with ngrams.

- petastorm/etl/dataset_metadata.py
- petastorm/etl/petastorm_generate_metadata.py
- petastorm/fs_utils.py
- petastorm/tests/test_dataset_metadata.py
- petastorm/tests/test_end_to_end.py
- petastorm/tools/copy_dataset.py
#287 
When using the `materialize_dataset()` context manager, the cleanup steps attempts to write rowgroup metadata to the generated files via `_generate_num_row_groups_per_file()`. This method attempts to serialize `pyarrow_filesystem` object, which works if the spark driver and executors reference the same JVM process (i.e. if they are on the same machine). However, if multiple processes are used, the `pyarrow_filesystem` object will contain invalid references. 
Instead of `_generate_num_row_groups_per_file()` serializing the filesystem object, it should serialize a method for recreating the filesystem object on the spark executor, which can then be called to correctly reference files and obtain metadata.
> #287 - fix materialize_dataset() serialization error by serializing fs factory

- petastorm/tests/conftest.py
- petastorm/tests/test_common.py
- petastorm/tests/test_parquet_reader.py
- petastorm/tests/test_tf_dataset.py
- petastorm/tests/test_tf_utils.py
Python 3 does not support namedtuples with > 255 fields. #323 attempts to solve this issue.
These tests can be used to verify that the fix works. Currently the tests are disabled for Python 3
and we need to reenable them once the solution is in place.
> Adding unit tests to verify that Petastorm can work with existing parquet stores with > 255 columns.

- README.rst
- examples/mnist/pytorch_example.py
- examples/mnist/tests/test_pytorch_mnist.py
- petastorm/pytorch.py
- petastorm/tests/test_pytorch_dataloader.py
- petastorm/tests/test_pytorch_utils.py
- petastorm/transform.py
- petastorm/workers_pool/exec_in_new_process.py
Two commits in this PR:
- Use `dill` in `exec_in_new_process.py` : allows a wider variety of types to be passed to a worker process
- Removing `transform` argument from `DataLoader`: `transform` was a 'toy' implementation which was not useful since it ran on the main thread. Now we have `transform_spec` argument in `make*reader` functions that allow to run a transform on a worker thread
> Deprecate DataLoader transform argument

- petastorm/tests/test_unischema.py
- petastorm/unischema.py
Due to this pyarrow bug, we cannot use some fields in our datasets.
However, since these fields are not always mandatory for the use case to be implemented and since data duplication would be too costly, we can afford to ignore it directly when loading the parquet file.
> ARROW-1644/1599:  Excludes list inside structs fields from schema inference.

- .pylintrc
- petastorm/hdfs/namenode.py
pyarrow==0.12.1 assume hdfs connect arguments are unicode. Make sure we pass unicode.
(tested using python 2/3 and pyarrow 0.12.1 and 0.11.1)
> Make hdfs connect arguments unicode strings

- petastorm/tests/test_unischema.py
- petastorm/unischema.py
Some Criteo parquet datasets contain unsupported fields.
The current behaviour of Petastorm is to raise a ValueError in the from_arrow_schema()::_numpy_and_codec_from_arrow_type() method when such a field is detected.
This patch introduces an optional argument to print only a warning and ignore the field instead of raising an exception, thus enabling the use of the 'partial' dataset.
> Add an option to warn and ignore unsupported columns

- petastorm/tests/test_unischema.py
- petastorm/transform.py
- petastorm/unischema.py
"name" is a likely name for a user column. Existing `Unishema.name` attribute conflicts with
dynamically generated attributes. We rename `Unischema.name` into `Unischema._name`. If there
is a conflict between user field and existing attribute, we emit a warning and skip dynamic
attribute creation for that field.
> Rename `Unischema.name` to `Unischema._name` property to avoid conflict user fields named `name`.

- petastorm/tests/test_unischema.py
- petastorm/transform.py
- petastorm/unischema.py
Reverts uber/petastorm#328
Was breaking legacy dataset read test.
> Revert "Rename `Unischema.name` to `Unischema._name` property to avoid conflict user fields named `name`."

- NOTICE
- petastorm/namedtuple.py
- petastorm/tests/test_parquet_reader.py
- petastorm/tests/test_tf_dataset.py
- petastorm/tests/test_tf_utils.py
- petastorm/unischema.py
- petastorm/utils.py
Many of our datasets have more than 255 fields.
This commit provides an alternative namedtuple implementation 'namedtuple2' to support more than 255 fields with the Python 3.6 interpreter.
> Unischema supports Parquet schema with more than 255 fields

- petastorm/py_dict_reader_worker.py
- petastorm/reader_impl/row_group_loader.py
- petastorm/tests/test_common.py
- petastorm/tests/test_pytorch_dataloader.py
- petastorm/tests/test_tf_dataset.py
- petastorm/tests/test_tf_utils.py
The fix is to use appropriate switch in a call to pyarrow table to pandas conversion.
> Fix #333: If integer_object_nulls is set to False, nullable integer fields are return as floats

- petastorm/reader.py
- petastorm/tests/test_end_to_end.py
- petastorm/workers_pool/tests/test_ventilator.py
- petastorm/workers_pool/ventilator.py
Resets ``Reader`` state and allows to fetch more samples once the ``Reader`` finished reading all epochs,
as specified by the ``num_epochs`` parameter.
Once all samples were read from a reader, an attempt to fetch new sample (e.g. ``next(reader)`` would raise
``StopIterationError``. You can reset the reader to the original state and restart reading samples
calling ``reset()``.
We do not support calling ``reset()`` until all samples were consumed. ``NotImplementedError``
will be raised if a user attempt to do so.
> Add `Reader.reset()` method.

- petastorm/etl/dataset_metadata.py
- petastorm/etl/rowgroup_indexing.py
In 0.13, an extra parameter is added to the `ParquetDatasetPiece` constructor.
This changes the position of the arguments.
As a solution, pass arguments as named arguments.
> pyarrow 0.13 compatbility: ParquetDatasetPiece constructor signature mismatch

- petastorm/errors.py
- petastorm/reader.py
- petastorm/reader_impl/reader_v2.py
- petastorm/tests/test_end_to_end.py
This helps find errors earlier: a surprising use case is if a user passes num_epochs=None, uses sharding, and does not get any samples.
> Raise a `NoDataAvailableError` if all rowgroups are filtered by predicate/rowgroup-selector or sharding.

- petastorm/selectors.py
- petastorm/tests/test_end_to_end.py
It seems that currently `rowgroup_selector` parameter in `make_reader` allows filtering using only a single indexed field. This is limiting, since one might need to filter a dataset according to multiple indexed fields. Predicates can be used in combination with rowgroup_selector to get the desired data, but this approach might require extensive I/O against the data repository.
The code below solves this issue by adding the functionality to filter row groups using multiple indexes with IntersectIndexSelector and UnionIndexSelector.
> Multiple index selectors

- petastorm/local_disk_arrow_table_cache.py
Workaround for https://issues.apache.org/jira/browse/ARROW-5260
unless we try to serialize something before deserialize_components is called, we would crash with a sigsegv
> Fix `LocalDiskArrowTableCache` that was crashing due to arrow bug

- .travis.yml
Current hypothesis that travis tries to cleanup after docker build, but has no permissions (since docker writes out *pyc files as root).
Cleaning ourselves would hopefully solve the release failure.
> Cleanup at the end of travis build and deploy only for one build matrix configuration

- petastorm/fs_utils.py
- petastorm/hdfs/tests/test_hdfs_namenode.py
- petastorm/tests/test_fs_utils.py
We were accidentally capturing FilesystemResolver and its attributes in filesystem_factory returned to the user.
This resulted in failures if attempted to pass the factory to spark executors.
By making FilesystemResolver unpickable we can now cover this accidental pickling by unit tests (which were updated)
> Guarantee filesystem_factory returned from FilesystemResolver is serializable

- petastorm/etl/dataset_metadata.py
- petastorm/etl/petastorm_generate_metadata.py
- petastorm/etl/rowgroup_indexing.py
- petastorm/fs_utils.py
- petastorm/hdfs/namenode.py
- petastorm/hdfs/tests/test_hdfs_namenode.py
- petastorm/tests/test_fs_utils.py
- petastorm/tools/copy_dataset.py
User is added as optional parameters for filesystem resolver.
Various entry points for file system resolver (materialize dataset, row group indexer, etc) provide the spark user name to filesystem resolver. Usually the spark user name is gotten from HADOOP_USER_NAME environment variable
> Adding the user parameter when pyarrow.hdfs.connect and using spark user when possible 

- examples/mnist/generate_petastorm_mnist.py
Default row-group size is 256MB. We end up having just a single rowgroup of 60K rows. It is really awkward to read from such a dataset since all 60K images need to be decoded before user gets a single row.
With smaller rowgroup size, a user gets first samples right away making it easier to work with the code.
> Reduce the size of a rowgroup for mnist example.

- petastorm/arrow_reader_worker.py
In ArrowReaderWorker, when trying to load a column of list type, where list is of variable length an error needs to be thrown. This error is defined here.
However the error fails while printing
Instead of
`', '.join({values.shape[0] for value in ....})`
It should be
`', '.join({str(values.shape[0]) for value in ....})`
> Cast int to string in Runtime error (ArrowReaderWorker)

- petastorm/predicates.py
- petastorm/tests/test_predicates.py
We convert all values to string and then calculate the hash as the value was a string.
> Make sure in_pseudorandom_split works also with non-string fields.

- petastorm/reader_impl/shuffling_buffer.py
Previous implementation used list. pop(0) from a list is very expensive.
Timing of the new code shows x25 speedup.
> Use deque in NoopShufflingBuffer.

- petastorm/transform.py
The current `ValueError` was missing `format` and had `%s` which were not being correctly used.
Also updated the docstring to say that `removed_fields` is `Optional[list]` instead of `Optional`
> Throw the correct error in Transform.py

- petastorm/tests/test_common.py
- petastorm/tests/test_decode_row.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_unischema.py
- petastorm/unischema.py
- petastorm/utils.py
The goal is twofold:
- Spare users' effort of defining codec attribute for fields that are scalars and we can easily decode/encode the values ourselves.
- Make it possible for a user to skip the encoding/decoding mechanism (this is an experimental feature at the moment)
If no codec is specified, we try to deduce spark type from `UnischemaField`''s `numpy_dtype` attribute when possible. If `numpy_dtype` is not set or different from a numpy scalar or a `Decimal`, we just pass it through.
> Make 'codec' and 'nullable' optional UnischemaField arguments

- petastorm/__init__.py
- petastorm/ngram.py
- petastorm/tests/test_ngram.py
- petastorm/tests/test_transform.py
- petastorm/transform.py
- petastorm/weighted_sampling_reader.py
- Don't fail transform if unknown fields are encountered. Warn instead.
- Fixing ngram equivalence check in weighted_sampling_reader.
- Adding ngram eq operator implementation
> Fixups that simplify working with transforms and WeightedSamplingReader

- .pylintrc
- petastorm/reader.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_tf_utils.py
- petastorm/tests/test_weighted_sampling_reader.py
Encountered this issue in #432 and #396. User tried reading after their context manager
has exited, which resulted in unexpected behavior.
> Raise an error if a user tries to read from a reader after it was stopped

- petastorm/workers_pool/process_pool.py
- petastorm/workers_pool/tests/test_workers_pool.py
Added `zmq_copy_buffers` argument to the `ProcessPool` constructor. It controls whether we will use copy=True/False argument of recv_multipart.
Unfortunately, copy=False does not play nice with Python GC (at least with its default values of thresholds) and will result in wild memory footprint swings when working with large buffers (such as images).
Copying memory appears to be a safer option for common user scenario. Control over this setting is currently not exposed to users of `make_reader` or `make_batch_reader` interfaces, but may be added in the future.
In advanced scenarios, users may construct `Reader` object manually and configure it with a custom configured `ProcessPool` object.
> Do not use zero-memory-copy feature of zmq to prevent large memory footprint swings.

- petastorm/reader.py
> Clarify that `results_queue_size` affects number of row-groups stored in the queue and not rows.

- petastorm/fs_utils.py
According to #279 an issue with pickling `ParseResult` accross pyspark
driver-executor border may result in a corrupt `ParseResult` instance
that is lacking `hostname` attribute.
We try to fix the issue by marshalling url string instead of the
`ParseResult` instance.
> Fix missing hostname attribute in ParseResult

- petastorm/arrow_reader_worker.py
- petastorm/tests/test_parquet_reader.py
Observed the following failure with pyarrow 0.14.1 and python 2.7:
```
from petastorm.reader import Reader, make_batch_reader
path = '/tmp/train'
schema_fields = ['features']
batch_reader = make_batch_reader('file://'+path, schema_fields=schema_fields)
print(batch_reader.next())
Traceback (most recent call last):
File "test.py", line 9, in <module>
print(batch_reader.next())
File "/home/.../lib/python3.7/site-packages/petastorm/reader.py", line 616, in next
return self.__next__()
File "/home/.../lib/python3.7/site-packages/petastorm/reader.py", line 610, in __next__
return self._results_queue_reader.read_next(self._workers_pool, self.schema, self.ngram)
File "/home/.../lib/python3.7/site-packages/petastorm/arrow_reader_worker.py", line 79, in read_next
return …
```
> Fix failure due to partition fields values returned by pyarrow read.

- petastorm/codecs.py
- petastorm/tests/test_codec_compressed_image.py
Allows user to query the codec type: png/jpeg
> Adding image_codec accessor to CompressedImageCodec

- docker/Dockerfile
Docker.io build currently fails with `MemoryError` caused by `pip3.6 install` of pytorch. Trying to apply a solution as proposed in  [here](https://discuss.pytorch.org/t/memory-error-when-installing-pytorch/8027/6)
> Fixing MemeoryError when building docker image on docker.io

- petastorm/etl/dataset_metadata.py
- petastorm/tests/test_common.py
- petastorm/tests/test_parquet_reader.py
This bug manifests in either:
- `pyarrow.lib.ArrowIOError: The file only has <X> row groups, requested metadata for row group: <Y>` (where <X> and <Y> are integers) exception, or:
- silently - some rows in a dataset might have been silently ignored.
This issue occured when:
- using `make_batch_reader`
- number of row-groups in different parquet files (pieces) is different.
The issue was in introduced in petastorm 0.7.7
Resolves #447
> Fix incorrect counting of number of row-groups per piece.

- petastorm/arrow_reader_worker.py
Using `values` property instead of the deprecated `as_matrix()` function.
Resolves #479
> Fixing pandas 1.0 compatibility issue (as_matrix)

- petastorm/tests/test_parquet_reader.py
Adding two tests, for selecting just an invalid column and both invalid and valid columns, for parquet reader.
Creating a new PR for this as PR #445 is having conflicts with master, probably due to my following the wrong git advice on the internet...
> New PR adding tests for requesting invalid columns from parquet reader

- petastorm/py_dict_reader_worker.py
- petastorm/tests/test_end_to_end.py
I noticed that TransformSpecs were not being applied if there was also a row predicate specified, this PR updates the `_load_rows_with_predicate` function to match https://github.com/uber/petastorm/blob/master/petastorm/py_dict_reader_worker.py#L184
> assign transform result in _load_rows_with_predicate

- petastorm/tests/test_unischema.py
- petastorm/unischema.py
The warning was occuring when both legacy and the new rule produced the
same overall set of fields, but maybe in different order. Although, both
rules would behave the same from the user perspective, they would see a
warning. The warning would be bogus because it wouldn't contain any
field names.
> Fix spurious legacy-regex rule warning

- petastorm/arrow_reader_worker.py
- petastorm/reader.py
- petastorm/tests/test_parquet_reader.py
Make `make_batch_reader` TransformSpec support output multi-dimensional array type.
The project: Simplify data conversion from Spark to TensorFlow: Spark converter basic implementation is implemented via `make_batch_reader` API. And user may want to do some preprocessing and return some tensor (multi-dimensional array) in the preprocess function.
Currently, `make_batch_reader` TransformSpec func only allow return one-dimensional array because of pyarrow format limitation.
This PR address this issue. The approach is:
Flatten the multi-dimensional array returned by TransformSpec func, and in `ArrowReaderWorkerResultsQueueReader` loading data code, reshape back to the specified shape.
Note reshape is a in-place operation so it won't affect performance.
~~~python
from petastorm import …
> Make `make_batch_reader` TransformSpec support output multi-dimensional array type.

- petastorm/codecs.py
- petastorm/tests/test_codec_scalar.py
- petastorm/tests/test_unischema.py
Validating types earlier in the code execution paths with a clear
message is better than vague errors from downstream code.
> Verify that scalars and not arrays are passed to a ScalarCodec instance

- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
Add `converter.make_tf_dataset()` with advanced params.
~~~python
class SparkDatasetConverter(object):
"""
A `SparkDatasetConverter` object holds one materialized spark dataframe and
can be used to make one or more tensorflow datasets or torch dataloaders.
The `SparkDatasetConverter` object is picklable and can be used in remote
processes.
See `make_spark_converter`
"""
def make_tf_dataset(
self,
batch_size=32,
prefetch=None,
num_epochs=None,
workers_count=4,
**petastorm_reader_kwargs
):
"""
Make a tensorflow dataset.
This method will do the following two steps:
1) Open a petastorm reader on the materialized dataset dir.
2) Create a tensorflow dataset based on the reader created in (1)
:param batch_size: The number of items to return per batch
:param prefetch: Prefetch size for tensorflow …
> Simplify data conversion from Spark to TensorFlow: support tensorflow dataset advance arguments

- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
For some filesystem like aws S3, there's an eventually consistency issue: after we materialized dataframe as parquet files, when use petastorm reader, the file may not be available immediately. We need wait at most 30 seconds to make sure all files are available. This is caused by S3 list operation eventually consistency.
> [ML-9743] Address S3 eventually consistency issue on S3-like filesystem

- petastorm/tests/test_spark_dataset_converter.py
- petastorm/tests/test_tf_utils.py
- petastorm/unischema.py
I set the inferred shape for array type field to be `(None,)` instead of `()`.
This will address issues on tensorflow dataset.
Test code:
```
import os
import pandas as pd
import sys
import numpy as np
from pyspark.sql.functions import pandas_udf
import tensorflow as tf
from petastorm import make_batch_reader
from petastorm.transform import TransformSpec
from petastorm.spark import make_spark_converter
spark.conf.set('petastorm.spark.converter.parentCacheDirUrl', 'file:/tmp/converter')
data_url = 'file:/tmp/0001'
data_path = '/tmp/t0001'
@pandas_udf('array<float>')
def gen_array(v):
return v.map(lambda x: np.random.rand(10))
df1 = spark.range(10).withColumn('v', gen_array('id')).repartition(2)
cv1 = make_spark_converter(df1)
with cv1.make_tf_dataset(batch_size=4, num_epochs=1) as dataset: …
```
> [ML-10156] Fix array type field inferred shape

- README.rst
The "Spark Converter API" section now contains minimalist examples of Spark -> Tensorflow and Spark -> PyTorch.
I also edited the section "PySpark and SQL" to make it better connected with the preceding section.
> Update Spark Converter API section in README.rst

- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
* Warn users if the intermediate file sizes are too small (<50mb)
* Warn users if set wrong parent cache dir. (Only in databricks environment)
> [ML-10160] Refine Spark dataset converter warning logs.

- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
Current code exists an issue that spark session will be created on spark executor.
This is because `_get_spark_session` being invoked by `_wait_file_available`, and `_wait_file_available` will be invoked from executor side.
So I fix it. I removed the config `petastorm.spark.converter.fileAvailabilityWaitTimeoutSecs`, the config is rarely used.
> Fix issue: spark session created on spark executor

- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
When the user wants to manually delete the cache files and create a new cache, they do:
~~~python
converter.delete()
converter = make_spark_converter(df)
~~~
Get error:
```
org.apache.spark.sql.AnalysisException: Path does not exist: file:/dbfs/ml/tmp/petastorm/QA/keras/20200407043623-appid-app-20200406162107-0000-d7d7cdfd-3739-48d0-9dc1-bffba08fff12;
```
Fix: We should cleanup cache metadata in SparkDatasetConverter.delete() besides deleting the data files.
> [ML-10366]  Fix bug: cleanup metadata in converter.delete()

- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
Problem: This warning below shows up even when there is only one partition, and the file list could be too long to read.
```
The median size (1333465) of these parquet files (file list...) is too small.Increase file sizes by repartition or coalesce spark dataframe, which will help improve performance.
```
Fix: 
1. Only print warning for (num_of_files > 1 && median file size < 50MB)
2. Remove the file list in the warning.
3. Provide the total size of the dataset and the threshold file size (50MB) in the warning to help users to decide how many partitions do they need.
Test:
Added unit test in `test_check_dataset_file_median_size`.
> Fix: The "median size too small" warning is too frequent

- petastorm/etl/dataset_metadata.py
- petastorm/tests/test_common.py
- petastorm/tests/test_end_to_end.py
- petastorm/unischema.py
Starting spark 2.4, "parquet.enable.summary-metadata" is deprecated and "parquet.summary.metadata.level" should be used to control creation of
`_summary` file. Updated the code to set
`parquet.summary.metadata.level=ALL` is petastorm `use_summary_metadata=True`
and `parquet.summary.metadata.level=NONE` otherwise.
> Use parquet.summary.metadata.level to control _summary file creation.

- petastorm/compat.py
- petastorm/tests/conftest.py
- petastorm/unischema.py
- petastorm/utils.py
No functionality change as we can see from:
```python
def add_metadata(self, metadata):
warnings.warn("The 'add_metadata' method is deprecated, use "
"'with_metadata' instead", FutureWarning, stacklevel=2)
return self.with_metadata(metadata)
```
Our CI does not test all pyarrow versions (just 0.12.1 and 0.15.1), so tried locally 0.13, 0.14 and 0.15)
> Replace deprecated Schema.add_metadata with Schema.with_metadata call.

- petastorm/fs_utils.py
- petastorm/reader.py
- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
Bug: If we execute the following code:
```python
spark.conf.set("petastorm.spark.converter.parentCacheDirUrl", "file:///url1")
converter1 = make_spark_converter(df)   # This works fine.
spark.conf.set("petastorm.spark.converter.parentCacheDirUrl", "file:///url2")
converter2 = make_spark_converter(df)
```
The last line will hit cache:
```The median size (1333465) of these parquet files (file:/url1/file_abc.parquet) is too small.Increase file sizes by repartition or coalesce spark dataframe, which will help improve performance.```
indicating that the new conf parent dir is not respected (still hitting the .../url1 dir).
Fix: We respect the conf change by adding an equality test against the parent cache dir.
> Fix bug: respect dynamically changed parent cache dir conf

- petastorm/spark/spark_dataset_converter.py
Removing the `reverse=True` to actually select the larger size when there is a tie.
> Fix Fix: The 'median size too small' warning is too frequent #538

- .travis.yml
- petastorm/tests/conftest.py
- petastorm/tests/test_spark_dataset_converter.py
- petastorm/tests/test_tf_autograph.py
- petastorm/tf_utils.py
- petastorm/unischema.py
Currently, for some function, TF2 autograph will fail.
See
https://github.com/tensorflow/tensorflow/issues/35765
https://github.com/tensorflow/tensorflow/issues/30149
https://github.com/tensorflow/autograph/issues/3
If autograph failed, the functions will be run eagerly and TF cannot optimize them. So we'd better address them.
~~~python
df1 = spark.range(100)
from petastorm.spark import make_spark_converter
spark.conf.set("petastorm.spark.converter.parentCacheDirUrl", "file:///dbfs/ml/tmp/petastorm/QA/bugs/")
converter1 = make_spark_converter(df1)
with converter1.make_tf_dataset(num_epochs=1) as dataset:
for batch in dataset:
print(batch.id)
~~~
* Before
Output includes:
```
WARNING:tensorflow:AutoGraph could not transform <function _NamedtupleCache.get at 0x7f0bfbe6f200> and will run it …
```
> Address several autograph failed issues for TF2

- docs/autodoc/api.rst
- petastorm/spark/spark_dataset_converter.py
1. Added a reference to the SparkDatasetConverter into API index.
2. Tweaked doc strings to make them compatible with doc autogeneration utility.
> Adding new SparkDatasetConverter documentation to the API section of autogenered docs.

- petastorm/gcsfs_helpers/gcsfs_wrapper.py
gcsfs returns name as [path]/part/, and in this case. Following code will set directories to list of empty strings.
```
directories = sorted([posixpath.split(x)[1]
for x in directories])
```
> handle names like [path]/part/

- petastorm/tests/test_weighted_sampling_reader.py
- petastorm/weighted_sampling_reader.py
Without this property, `make_petastorm_dataset` was crashing if `WeightedSamplingReader` reader was passed to it.
> Added last_row_consumed property to WeightedSamplingReader

- petastorm/hdfs/namenode.py
See: https://github.com/apache/arrow/pull/6432
Related Horovod issue: https://github.com/horovod/horovod/issues/2000
> Remove driver param for hdfs.connect when using pyarrow 0.17 and above

- .travis.yml
- mypy.ini
- petastorm/hdfs/tests/test_hdfs_namenode.py
- petastorm/pytorch.py
- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_benchmark.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_ngram_end_to_end.py
- petastorm/tests/test_spark_dataset_converter.py
- petastorm/tests/test_tf_utils.py
- petastorm/tests/test_unischema.py
- petastorm/unischema.py
- setup.py
Using mypy to run static type checking as part of travis build
Fixed some issues causing mypy to fail:
- Upgraded minimal torch and Pillow versions in `setup.py`
- Upgraded torch and Pillow in `.travis.yml`. This is a quick fix. A proper better way is to upgrade docker image used for the build.
- Rely on `unittest`'s `mock`
- Adding some type hints required by mypy
> Use mypy in our CI script

- README.rst
I found that the fully-functional hello world example code was great for approaching the project for the first time... but figuring out these imports was pretty time consuming, and I thought it might be nice to just embed them in the example.
> Add imports to README example.

- docs/release-notes.rst
- petastorm/etl/dataset_metadata.py
When reading parquet store directly from an s3 bucket, a separate piece is created for root directory.
This is not a real "piece" and we won't have row_groups_per_file recorded for it.
> Ignore an invalid piece created for a subdirectory when a dataset is stored in an s3 bucket subdirectory

- docs/release-notes.rst
- petastorm/reader.py
- petastorm/tests/test_reader.py
- petastorm/workers_pool/process_pool.py
> Add a flag to factory methods to allow zmq copy buffers to be disabled

- docs/release-notes.rst
- petastorm/etl/dataset_metadata.py
- petastorm/fs_utils.py
s3, s3a and s3n url protocols can be explicitly specified when saving petatorm datasets.
Fixed a bug on petastorm dataset write execution path previously preventing writing directly to s3 buckets.
Tested: modified `examples/generate_external_dataset.py` and `examples/python_hello_world.py` to write/read from s3 bucket using s3a and s3n buckets (wasn't able to properly configure s3 authentication to check that). Was able to write/read data successfully.
> Allow users to use s3, s3a and s3n protocols when saving / reading datasets

- docs/release-notes.rst
- petastorm/fs_utils.py
- petastorm/tests/test_fs_utils.py
- setup.py
Enforce the minimal s3fs version at which S3FSWrapper is not needed. Fixes #609.
> Bugfix: S3FSWrapper is deprecated at s3fs 0.5.0

- docs/release-notes.rst
- petastorm/reader.py
- petastorm/tests/test_parquet_reader.py
Makes it easier to detect user logic error, as it makes no sense to create a reader that loads no data from storage.
> Raising an error if an empty list of columns is selected by a user

- petastorm/pytorch.py
- petastorm/tests/test_weighted_sampling_reader.py
- petastorm/weighted_sampling_reader.py
- petastorm.pytorch.DataLoader expects the field is_batched_reader in the reader. WeightedSamplingReader does not have this field. It seems to be replaced by the property: batched_output.
- petastorm.pytorch.DataLoader expects the functions stop() and join() from the reader. WeightedSamplingReader does not have these functions. This PR adds these functions.
> bug with weighted_sampling_reader and pytorch

- docs/release-notes.rst
- petastorm/etl/dataset_metadata.py
- petastorm/fs_utils.py
- petastorm/reader.py
Support on-premise s3-compatible storage. User can now pass an instance of pyarrow filesystem to `make_reader` and `make_batch_reader` functions.
> Support on-premise s3-compatible storage.

- petastorm/arrow_reader_worker.py
- petastorm/tests/test_parquet_reader.py
Records returned by `make_batch_reader` are returned as a dictionary of coalesced numpy arrays. In order to properly batch multiple rows together, all fields must have the same dimension. If a user passes an shape that have some variable dimensions, multiple rows won't coalesce properly.
This PR issues a clear message.
See also: #633
> Raise an explicit error when TransformSpec is given a shape with a variable dimension

- docs/release-notes.rst
- petastorm/pytorch.py
- petastorm/tests/test_pytorch_dataloader.py
Also add comments of setting shuffling_queue_capacity correctly when
enablding in memory cache.
Fix #642
> Tests: fix the unit test of batched dataloader with in-memory cache

- .travis.yml
- examples/mnist/tests/test_pytorch_mnist.py
Having a loose `pip install -U numpy` in .travis.yml resulted in
non-deterministic version of numpy and as a result a broken build.
Currently fixing the version to an older numpy 1.19 and will upgrade CI
versions of pyarrow and numpy in cohort in the following PRs.
> Fixate numpy version used in build

- petastorm/tf_utils.py
A proper numpy dtype to use is `np.bool_` and not `np.bool`. `np.bool_` is already present in the numpy/tf mapping table.
This fixes mypy static check that would fail if we upgrade pyarrow to version 2 or higher.
> Fix mypy test: removing np.bool from tf_utils numpy-to-tf dtype conversion

- docs/release-notes.rst
- petastorm/reader.py
- petastorm/tests/test_end_to_end.py
Splitting row groups by % num_shards is not a good idea to split data.
This commit introduce a shard_seed parameter to random shuffle row
groups before sharding.
> Reader: shuffle row groups before sharding.

- petastorm/tests/test_tf_dataset.py
- petastorm/tf_utils.py
We can cache first iteration result then use repeat() to do multiple
epochs.
> tf_dataset: add unit test to verify repeat() works after cache()

- docs/release-notes.rst
- petastorm/tests/test_common.py
- petastorm/tests/test_unischema.py
- petastorm/unischema.py
Previously, an error was raised when an unsupported type (e.g. nested structure) was found in the datasource. Relaxing the constraint so that fields with unknown types would be silently ignored - simply won't show up in the loaded data.
> Allow opening parquet stores with unsupported types.

- docs/release-notes.rst
- petastorm/py_dict_reader_worker.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_parquet_reader.py
Code was crashing since ParquetDataset's (pyarrow) partition_names attribute was set to None when the ParquetDataset object instance was created from a parquet file and not parquet directory.
> Fix a failure when reading data from a parquet file (and not a parquet directory)

- docs/release-notes.rst
- petastorm/workers_pool/thread_pool.py
Python 3.8 is the last version supporting isAlive method. It was renamed to is_alive. Resolves #692.
> Python 3.9 isAlive -> is_alive compatibility fix

- .github/workflows/unittest.yml
Not sure why a bunch of functions such as `_numpy_and_codec_from_arrow_type` are now flagged as too complex. Bump
up complexity threashold, as the functions that are flagged look reasonable to me.
> Unbreak "C901 ... too complex" flake failures in CI

- petastorm/reader_impl/arrow_table_serializer.py
This fixes a warning about usage of a deprecated function.
> Use pyarrow.ipc.open_stream instead of legacy pyarrow.open_stream

- .github/workflows/unittest.yml
- petastorm/tests/conftest.py
- petastorm/tests/test_generate_metadata.py
- petastorm/tests/test_ngram_end_to_end.py
- petastorm/workers_pool/exec_in_new_process.py
- setup.py
Renamed config action names to better describe versions in the build.
> Use py3.9 for all CI tests, except one that uses 3.7

- petastorm/tests/test_common.py
That's because we no longer support 0.15
> Don't exclude fields not supported by pyarrow 0.15 from test data.

- docs/release-notes.rst
- petastorm/etl/legacy.py
- petastorm/tests/test_ngram_end_to_end.py
Based on #637: whitelists a set of packages which classes can be unpickled. Prevents unpickling a malicious class that may invoke `os.execute` or a similar other malicious function calls.
> Security fix for arbitrary code execution.

- .github/workflows/unittest.yml
- docs/release-notes.rst
- petastorm/arrow_reader_worker.py
- petastorm/py_dict_reader_worker.py
- petastorm/reader.py
- petastorm/unischema.py
Removing a hack where we manually override pyarrow's `dataset.partitions` property because of an assumption of other parts of code that the attribute is always set and iterable.
pyarrow 5.0 breaks as it protects the attribute against modification.
We fix the issue by explicitly checking for `dataset.partitions` being `None` in relevant parts of petastorm code.
Add a unittest configuration to cover pyarrow 3, 4, and 5.
Resolves #707
> Do not attempt to override pyarrow's dataset.partitions attribute

- docker/Dockerfile
Tensorflow2 conflicts with numpy 1.20.1
Error example is:
```
#30 26.12 ERROR: Cannot install numpy==1.20.1, pyarrow==3.0.0 and tensorflow==2.5.0 because these package versions have conflicting dependencies.
#30 26.12
#30 26.12 The conflict is caused by:
#30 26.12     The user requested numpy==1.20.1
#30 26.12     pyarrow 3.0.0 depends on numpy>=1.16.6
#30 26.12     tensorflow 2.5.0 depends on numpy~=1.19.2
#30 26.12
#30 26.12 To fix this you could try to:
#30 26.12 1. loosen the range of package versions you've specified
#30 26.12 2. remove package versions to allow pip attempt to solve the dependency conflict
```
> Fix package versions in Dockerfile

- docs/release-notes.rst
- petastorm/workers_pool/exec_in_new_process.py
- petastorm/workers_pool/exec_in_new_process_entrypoint.py
Restructure process_pool implementation code in a way that resolves `RuntimeWarning: 'petastorm.workers_pool.exec_in_new_process' found in sys.modules after import of package 'petastorm.workers_pool', but prior to execution of 'petastorm.workers_pool.exec_in_new_process'; this may result in unpredictable behaviou when using process pool` warning.
In this diff we break main entry point from `exec_in_new_process.py` file into two a separate `exec_in_new_process_entrypoint.py`.
Resolves #585
> Get rid of RuntimeWarning when using process pool

- docs/release-notes.rst
- petastorm/hdfs/namenode.py
- petastorm/hdfs/tests/test_hdfs_namenode.py
Resolves #724. Hadoop 3 configuration file allows more than two namenodes to be available. Petastorm code was assuming up to two namenodes in the configuration file. This PR allows for unbound number of namenodes to be present.
> Allow more than two namenodes in hdfs configuration file.

- docs/release-notes.rst
- petastorm/reader_impl/pickle_serializer.py
[Pickle protocol 5](https://www.python.org/dev/peps/pep-0574/) allows for zero-copy pickling of numpy arrays, but protocol version 4 remains the default for Python 3.8 onwards. When loading datasets with large numpy arrays and `reader_pool_type="process"`, using protocol 5 significantly improves serialization time and overall performance.
Protocol 5 is only available in Python 3.8 and onwards, so for backwards and forwards compatibility with future pickle protocol improvements we specify `pickle.HIGHEST_PROTOCOL`.
```
import time
import numpy as np
from petastorm.reader_impl.pickle_serializer import PickleSerializer
s = PickleSerializer()
data = [np.random.random((1000, 1000)) for _ in range(10)]
t = time.time()
for x in range(100):
_ = s.deserialize(s.serialize(data))
print(time.time() - …
```
> Use highest available pickle protocol when serializing

- petastorm/predicates.py
- petastorm/pytorch.py
- petastorm/reader.py
Import ABC from `collections` was deprecated and removed in Python 3.10. Use `collections.abc` .
> Import ABC from collections.abc for Python 3.10 compatibility

- .github/workflows/unittest.yml
Also dropped archaic pyarrow 0.17.1 from the CI.
> Upgrade CI to use latest packages of tf,pyarrow,numpy in 'latest' CI configuration

- petastorm/workers_pool/process_pool.py
- petastorm/workers_pool/tests/test_workers_pool.py
`process_iter` is very slow for checking if a process is alive. `pid_exists` is more efficient.
See: https://psutil.readthedocs.io/en/latest/index.html?highlight=process_iter#psutil.pid_exists
> Replace process_iter by pid_exists

- petastorm/reader_impl/pytorch_shuffling_buffer.py
- petastorm/tests/test_shuffling_buffer.py
Avoid creating many copies in _make_batch().
Fix #763
> PyTorch: improve memory-efficiency in batched non-shuffle buffer

- docs/release-notes.rst
- petastorm/arrow_reader_worker.py
- petastorm/py_dict_reader_worker.py
- petastorm/reader.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_parquet_reader.py
- petastorm/tests/test_reader.py
- petastorm/workers_pool/ventilator.py
- Allow shuffle inside every single row group in reader.
- Also use a shuffle seed to generate reproducible shuffle results across: single row shuffle, row groups shuffle in ventilator and sharding.
> Reader: enable shuffling inside every row group

- docs/release-notes.rst
- petastorm/reader.py
- petastorm/tests/test_parquet_reader.py
The default results_queue_size used in make_batch_reader is 50. This will lead to OOM exception while loading big datasets with thread reader pool type. By exposing results_queue_size parameter via make_batch_reader api, the user is able to control the prefetched data size which in turns will help to alleviate OOM issue.
> Support results_queue_size parameter in make_batch_reader api

- docs/release-notes.rst
- petastorm/spark/spark_dataset_converter.py
- petastorm/tests/test_spark_dataset_converter.py
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>
Make `make_spark_converter` supports creating converter from a saved dataframe path.
In this case, we can skip the step of materializing spark dataframe that might be slow.
> Make `make_spark_converter` supports creating converter from a saved dataframe path

- .github/workflows/unittest.yml
- petastorm/arrow_reader_worker.py
- petastorm/reader.py
- petastorm/tests/test_end_to_end.py
- petastorm/tests/test_tf_dataset.py
- petastorm/workers_pool/tests/test_workers_pool.py
- petastorm/workers_pool/thread_pool.py
- petastorm/workers_pool/ventilator.py
- setup.py
This PR addresses the issue where the reader doesn't give reproducible data order for multiple workers when shuffling is disabled or seed is set. The following changes are made to address the issue:
1. Ventilator Queue Modifications: Each worker now has a separate ventilator queue, ensuring deterministic data ordering through a round-robin strategy and eliminating race conditions.
2. np.default_rng(): The switch from np.random.RandomState() to np.default_rng() provides reproducible shuffling, ensuring consistent outcomes when a seed is provided.
3. Result Queue Improvements: Individual result queues for each worker have been implemented. Results are collected in a round-robin manner.
The following behavior is expected as a result of this change:
1. Shuffling = False, Deterministically …
> Support reproducible ordering in Petastorm
